FROM node:23-alpine AS build

WORKDIR /app

RUN apk add util-linux

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

ENV BACKEND_URL=http://localhost:3000

HEALTHCHECK --interval=5m --timeout=3s \ 
    CMD curl -f http://localhost || exit 1

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]