# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/WebServer/frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
    
  - package-ecosystem: "npm"
    directory: "/WebServer/backend"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/WebServer/backend"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/WebServer/frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"