# Utilisation de l'image Node pour construire l'application Express
FROM node:23-alpine AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier le package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm ci --omit=dev

# Copier le code source
COPY . .

# Etape de production
FROM node:alpine

WORKDIR /app

COPY --from=build /app/node_modules /app/node_modules

COPY . .

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=30s --start-period=30s \
    CMD node healthcheck.js

# Commande pour exécuter l'application
CMD ["npm", "start"]
