version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 8009:3000/tcp
      - 8010:80/tcp
      - 8011:443/tcp
    volumes:
      - /srv/appdata/adguard/workdir:/opt/adguardhome/work
      - /srv/appdata/adguard/confdir:/opt/adguardhome/conf
    environment:
      TZ: Europe/Brussels
    restart: unless-stopped
    networks:
      - haeliseu_network

networks:
  haeliseu_network:
    external: true