name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write  # Permet de modifier (fusionner) les PRs

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'  # S'assure que l'auto-merge ne concerne que Dependabot
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier les conditions d'automerge
        uses: pascalgn/automerge-action@v0.16.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le secret GitHub Token
          # Pour définir la méthode de merge (merge, squash, rebase), il faut définir merge_method dans les entrées spécifiques de l'action
          merge_method: 'merge'  # Spécifie la méthode de fusion
