name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier les conditions d'automerge
        uses: pascalgn/automerge-action@v0.16.4
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          merge_method: "merge"
          # Optionnel : définir des labels spécifiques
          # label: "automerge"
